from termcolor import colored
import requests

def report():
 #requests.get(f'https://eovzlu8cd49gpu1.m.pipedream.net/?tool=xssReport:{list55}')
 print(colored('''
____________________________________________________________________________
[                                                                          ]
[     ______             ___               ______               ______     ]
[     SIMPLE     -       BUG        -      REPORT        -      WRITER     ]
[                                                                          ]
[__________________________________________________________________________]

                         <+developed by m00n+>
                           
  [1]          =       nickname[+] | poc step[5] | parameter[-] | payload[1]
  [2]          =       nickname[+] | poc step[7] | parameter[+] | payload[1]
  [3]          =       nickname[-] | poc step[5] | parameter[+] | payload[5]
 
 ''','red'))
 samp1=int(input(colored("Choose your sample report [1] [2] [3]   >",color="blue")))
 if (samp1==1):
  print(colored("                                ________________________1_____________________",color="blue"))
  print(colored("                                |WRITE DOWN YOUR INFORMATION AND ABOUT TARGET|",color="green"))
  print(colored("                                ------------------------1---------------------",color="blue"))
  name=input(colored("Your Fucking Nickname   >",color="blue"))
  countr=input(colored("Your Fucking Country   >",color="blue"))
  vulname=input(colored(" Vulnerable name   >",color="blue"))
  tdomain=input(colored("Target Domain 	>",color="blue"))
  vurl=input(colored("Vulnerability Url   >",color="blue"))
  vpayload=input(colored("Payloads   >",color="blue"))
  risk=input(colored("Risk on system   >",color="blue"))
  add_info=input(colored("Additional Information  >",color="blue"))
  pocst1=input(colored("poc step1 [put blank if you dont need step] :",color="white"))
  pocst2=input(colored("poc step2 [put blank if you dont need step] :",color="white"))
  pocst3=input(colored("poc step3 [put blank if you dont need step] :",color="white"))
  pocst4=input(colored("poc step4 [put blank if you dont need step] :",color="white"))
  pocst5=input(colored("poc step5 [put blank if you dont need step] :",color="white"))
  print(colored("                         --------------------",color="blue"))
  print(colored("                         |Your Report Result|",color="red"))
  print(colored("                         --------------------",color="blue"))
  print("Hello, admin and security team")
  print("My name is ",name,", i am white hat hacker from",countr,".")
  print("")
  print("I want to report you a bug or vulnerability from your domain: ",tdomain,)
  print("Vulnerability name : ",vulname,)
  print("The vulnerable URL :",vurl)
  print("Payload to trigger this Vulnerability :",vpayload)
  print("")
  print("POC steps below:")
  print("step1- ",pocst1,".")
  print("step2- ",pocst2,".")
  print("step3- ",pocst3,".")
  print("step4- ",pocst4,".")
  print("step5- ",pocst5,".")
  print("")
  print("Impact : ",risk)
  print("Additional Information From Me :")
  print(add_info)
  print("")
  print("I hope you will fix it soon...........") 
  print("Regards,")
  print(name,".")
 elif (samp1==2):
  print(colored("                                ________________________2_____________________",color="blue"))
  print(colored("                                |WRITE DOWN YOUR INFORMATION AND ABOUT TARGET|",color="green"))
  print(colored("                                ------------------------2---------------------",color="blue"))
  name=input(colored("Your Fucking Nickname   >",color="blue"))
  countr=input(colored("Your Fucking Country   >",color="blue"))
  vulname=input(colored(" Vulnerable name   >",color="blue"))
  tdomain=input(colored("Target Domain 	>",color="blue"))
  vurl=input(colored("Vulnerability Url   >",color="blue"))
  vpara=input(colored("Vulnerability Parameter  >",color="blue"))
  vpayload=input(colored("Payloads   >",color="blue"))
  risk=input(colored("Risk on system   >",color="blue"))
  pocst1=input(colored("poc step1 [put blank if you dont need step] :",color="white"))
  pocst2=input(colored("poc step2 [put blank if you dont need step] :",color="white"))
  pocst3=input(colored("poc step3 [put blank if you dont need step] :",color="white"))
  pocst4=input(colored("poc step4 [put blank if you dont need step] :",color="white"))
  pocst5=input(colored("poc step5 [put blank if you dont need step] :",color="white"))
  pocst6=input(colored("poc step6 [put blank if you dont need step] :",color="white"))
  pocst7=input(colored("poc step7 [put blank if you dont need step] :",color="white"))
  print(colored("                         --------------------",color="blue"))
  print(colored("                         |Your Report Result|",color="red"))
  print(colored("                         --------------------",color="blue"))
  print("Hello upserve security team,")
  print("My name is ",name,", i am white hat hacker from ",countr,".")
  print("")
  print("I want to report you a bug or vulnerability from your domain.")
  print("I found a ",vulname,"bug or vulnerability on ",tdomain) 
  print("URL :",vurl)
  print("Vulnerability Parameter :",vpara)
  print("Payload:",vpayload)
  print("Risk on system : ",risk)
  print("")
  print("Steps to reproduce:")
  print("step1- ",pocst1,".")
  print("step2- ",pocst2,".")
  print("step3- ",pocst3,".")
  print("step4- ",pocst4,".")
  print("step5- ",pocst5,".")
  print("step6- ",pocst6,".")
  print("step7- ",pocst7,".")
  print("")
  print("Thanks and i hope you will fix it soon......") 
 elif (samp1==3):
  print(colored("                                ________________________2_____________________",color="blue"))
  print(colored("                                |WRITE DOWN YOUR INFORMATION AND ABOUT TARGET|",color="green"))
  print(colored("                                ------------------------2---------------------",color="blue"))
  vulname=input(colored(" Vulnerable name   >",color="blue"))
  tdomain=input(colored("Target Domain   >",color="blue"))
  vurl=input(colored("Vulnerability Url   >",color="blue"))
  vpara=input(colored("Vulnerability Parameter  >",color="blue"))
  vpayload1=input(colored("Payload1   >",color="blue"))
  vpayload2=input(colored("Payload2   >",color="blue"))
  vpayload3=input(colored("Payload3   >",color="blue"))
  vpayload4=input(colored("Payload4   >",color="blue"))
  vpayload5=input(colored("Payload5   >",color="blue"))
  risk=input(colored("Write down impact   >",color="blue"))
  pocst1=input(colored("poc step1 [put blank if you dont need step] :",color="white"))
  pocst2=input(colored("poc step2 [put blank if you dont need step] :",color="white"))
  pocst3=input(colored("poc step3 [put blank if you dont need step] :",color="white"))
  pocst4=input(colored("poc step4 [put blank if you dont need step] :",color="white"))
  pocst5=input(colored("poc step5 [put blank if you dont need step] :",color="white"))
  print(colored("                         --------------------",color="blue"))
  print(colored("                         |Your Report Result|",color="red"))
  print(colored("                         --------------------",color="blue"))
  print("Hello admin team and security team...")                    
  print("I want to report you vulnerability ",vulname,"on domain ",tdomain)
  print("")
  print("Vulnerability URL:",vurl)
  print("")
  print("Vulnerability Parameter:",vpara)
  print("")
  print("Impact : ",risk)
  print("Available Payloads:")
  print("payload 1 :",vpayload1)
  print("payload 2 :",vpayload2)
  print("payload 3 :",vpayload3)
  print("payload 4 :",vpayload4)
  print("payload 5 :",vpayload5)
  print("Steps To Reproduce:")
  print("step1 -",pocst1)
  print("step2 -",pocst2)
  print("step3 -",pocst3)
  print("step4 -",pocst4)
  print("step5 -",pocst5)
  print("")
  print("Thanks and i hope you will fix it soon.....have a nice fix....")
 else:
  print(colored("error command!!!",color="red"))
 log_file = open('log/log.txt','a')
 log_file.write(f'[sub] simple report writer --> name {name} --> vulnerable url {vurl}\n')
 log_file.close()

report()
